//------------------------------------------------------------
// LiteCodeGen - 独立版绑定代码生成
//------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace LiteCodeGen.EditorTools
{
    /// <summary>生成两个文件的文本内容:主文件(手动) + Designer(自动)。</summary>
    public static class BindTemplates
    {
        private const string AutoHeader =
            "// <auto-generated>\n" +
            "//     此文件由 LiteCodeGen 自动生成,请勿手动修改。\n" +
            "//     修改节点结构后,回到根节点(BindRoot)Inspector 重新点\"生成代码\"。\n" +
            "//     手动逻辑请写在同名 .cs(非 Designer)文件中。\n" +
            "// </auto-generated>\n";

        /// <summary>主文件(逻辑文件):仅在不存在时创建。默认继承 MonoBehaviour;若配置了 BaseClassFullName 则继承之。</summary>
        public static string BuildMainFile(string className, string namespaceName, string baseClassFullName)
        {
            var cb = new CodeBuilder();

            cb.Line("// 逻辑文件:此文件可放心手改。");
            cb.Line("// 提示:该类与同目录下的 *.Designer.cs 为 partial 关系,Designer 文件每次生成会覆盖。");
            cb.Line();
            cb.Line("using UnityEngine;");
            cb.Line();

            WriteNamespaceBegin(cb, namespaceName);

            var baseType = string.IsNullOrWhiteSpace(baseClassFullName)
                ? "MonoBehaviour"
                : baseClassFullName;

            cb.Line(string.Format("public partial class {0} : {1}", className, baseType));
            cb.Open();
            cb.Line();
            cb.Line("private void Start()");
            cb.Open();
            cb.Line("// 在此编写启动逻辑(例如绑定按钮事件)");
            cb.Close();
            cb.Line();
            cb.Close();

            WriteNamespaceEnd(cb, namespaceName);
            return cb.ToString();
        }

        /// <summary>Designer 文件:每次生成都整体重写,仅包含绑定字段。</summary>
        public static string BuildDesignerFile(string className, string namespaceName, List<BindMark> marks, bool emitRegisterControl = false)
        {
            var cb = new CodeBuilder();

            cb.Line(AutoHeader);
            cb.Line();

            WriteNamespaceBegin(cb, namespaceName);

            cb.Line(string.Format("public partial class {0}", className));
            cb.Open();
            cb.Line();

            if (marks == null || marks.Count == 0)
            {
                cb.Line("// (无绑定标记)");
            }
            else
            {
                for (var i = 0; i < marks.Count; i++)
                {
                    var mark = marks[i];
                    if (!string.IsNullOrEmpty(mark.Comment))
                    {
                        cb.Line("/// <summary>");
                        cb.Line("/// " + mark.Comment);
                        cb.Line("/// </summary>");
                    }

                    cb.Line(string.Format("public {0} {1};", mark.TypeFullName, mark.MemberName));
                    cb.Line();
                }

                // 双路径 B 的受控索引登记（M4 §2.4 对接：Designer 字段同时进 UIBindIndex，
                // 受控 API 面与路径 A 汇合）。由 BindRoot.EmitRegisterControl 显式开关控制——
                // 不再按基类名字符串推断（原名含匹配会在基类改名后静默停止生成）。
                if (emitRegisterControl)
                {
                    cb.Line();
                    cb.Line("private void Awake()");
                    cb.Open();
                    var registered = 0;
                    for (var i = 0; i < marks.Count; i++)
                    {
                        var mark = marks[i];
                        var indexName = mark.Bind != null ? mark.Bind.BindName : null;
                        if (string.IsNullOrEmpty(indexName)) continue;
                        cb.Line(string.Format("RegisterControl(\"{0}\", {1});", indexName, mark.MemberName));
                        registered++;
                    }
                    if (registered == 0) cb.Line("// (无 BindName 登记——索引由运行期标记构建提供)");
                    cb.Close();
                }
            }

            cb.Close();

            WriteNamespaceEnd(cb, namespaceName);
            return cb.ToString();
        }

        private static void WriteNamespaceBegin(CodeBuilder cb, string namespaceName)
        {
            if (string.IsNullOrWhiteSpace(namespaceName))
            {
                return;
            }

            cb.Line("namespace " + namespaceName);
            cb.Open();
        }

        private static void WriteNamespaceEnd(CodeBuilder cb, string namespaceName)
        {
            if (string.IsNullOrWhiteSpace(namespaceName))
            {
                return;
            }

            cb.Close();
        }
    }
}
