// <auto-generated: scripts/gen-build-hash.py —— DO NOT EDIT。源：LiteSim.Core/Scripts + LiteNet/Proto + LiteNet/Protocol
// 的源码内容；改了 Sim 或协议后重跑生成器再生。>
namespace LiteNet
{
    /// <summary>
    /// 联机版本 hash（M10 前置）：覆盖判定逻辑（Sim）与协议（Proto/Protocol）的源码内容，
    /// **两端（客户端/服务器）必须一致**——不一致 = 逻辑或协议版本不同 = 必然分叉。
    /// 用途：`JoinRequest.build_hash` 握手校验 + 启动期断言（不等 → 拒绝进房，§40/§380）；
    /// 生成规则见 `scripts/gen-build-hash.py`（含行尾归一化，保证跨机器可复现）；
    /// `Tests/LiteNet.Tests/BuildHashTests` 按同规则复算并比对（防止改了源码忘重跑）。
    /// </summary>
    public static class BuildHash
    {
        /// <summary>当前构建的版本 hash（16 位小写 hex）。</summary>
        public const string Value = "c6e3af2923cffe39";
    }
}
