# -*- coding: utf-8 -*-
# M10 前置：联机版本 hash 生成器（2026-09-17）。
# 用途：Join 握手 buildHash 校验 + 启动期断言——两端 hash 不等 → 拒绝进房（《状态同步实施方案》§40/§380）。
#
# 覆盖范围（**两端必须逐字节一致的东西**）：
#   Assets/LiteSim/Core/Scripts/**   —— 判定逻辑（Sim 内所有确定性行为）
#   Assets/LiteNet/Proto/**          —— 协议单源（.proto + 生成物）
#   Assets/LiteNet/Protocol/**       —— 打包解包纯函数
# 不覆盖：表现层/业务/UI（客户端差异不影响判定与协议）。
#
# 算法：按**相对路径（Ordinal）排序**后，逐个喂入 "相对路径\0<内容（行尾归一化）>" 到 SHA-256，
#       取前 16 个十六进制字符作 hash 值。确定性要点：
#   ① 排序固定（不依赖文件系统枚举顺序）
#   ② **行尾归一化**（CRLF/CR → LF）——否则不同机器 clone（git autocrlf）会算出不同 hash
#   ③ 排除自身输出（BuildHash.g.cs）与 bin/obj/.dotnet/.meta
#
# 重跑：改了 Sim 或协议后 → python scripts/gen-build-hash.py
# 守卫：Tests/LiteNet.Tests/BuildHashTests 会按同规则复算并与常量比对（L1 抓"忘了重跑"）
import hashlib
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGETS = [
    os.path.join('Assets', 'LiteSim', 'Core', 'Scripts'),
    os.path.join('Assets', 'LiteNet', 'Proto'),
    os.path.join('Assets', 'LiteNet', 'Protocol'),
]
OUT_FILE = os.path.join(ROOT, 'Assets', 'LiteNet', 'Protocol', 'BuildHash.g.cs')
SELF_NAME = 'BuildHash.g.cs'
SKIP_DIRS = {'bin', 'obj', '.dotnet', '__pycache__'}


def collect():
    files = []
    for target in TARGETS:
        base = os.path.join(ROOT, target)
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
            for name in filenames:
                if not name.endswith('.cs'):
                    continue
                if name == SELF_NAME or name.endswith('.meta'):
                    continue
                full = os.path.join(dirpath, name)
                rel = os.path.relpath(full, ROOT).replace('\\', '/')
                files.append((rel, full))
    files.sort(key=lambda x: x[0])          # Ordinal 排序（python 默认码点序，与 C# Ordinal 一致）
    return files


def normalize(raw):
    """行尾归一化：CRLF/CR → LF（跨机器 clone 一致性）。"""
    return raw.replace(b'\r\n', b'\n').replace(b'\r', b'\n')


def compute(files):
    h = hashlib.sha256()
    for rel, full in files:
        h.update(rel.encode('utf-8'))
        h.update(b'\x00')
        with open(full, 'rb') as f:
            h.update(normalize(f.read()))
    return h.hexdigest()[:16]


TEMPLATE = '''// <auto-generated: scripts/gen-build-hash.py —— DO NOT EDIT。源：LiteSim.Core/Scripts + LiteNet/Proto + LiteNet/Protocol
// 的源码内容；改了 Sim 或协议后重跑生成器再生。>
namespace LiteNet
{
    /// <summary>
    /// 联机版本 hash（M10 前置）：覆盖判定逻辑（Sim）与协议（Proto/Protocol）的源码内容，
    /// **两端（客户端/服务器）必须一致**——不一致 = 逻辑或协议版本不同 = 必然分叉。
    /// 用途：`JoinRequest.build_hash` 握手校验 + 启动期断言（不等 → 拒绝进房，§40/§380）；
    /// 生成规则见 `scripts/gen-build-hash.py`（含行尾归一化，保证跨机器可复现）；
    /// `Tests/LiteNet.Tests/BuildHashTests` 按同规则复算并比对（防止改了源码忘重跑）。
    /// </summary>
    public static class BuildHash
    {
        /// <summary>当前构建的版本 hash（16 位小写 hex）。</summary>
        public const string Value = "%s";
    }
}
'''


def main():
    files = collect()
    value = compute(files)
    with open(OUT_FILE, 'w', encoding='utf-8', newline='\n') as f:
        f.write(TEMPLATE % value)
    print('BuildHash.g.cs written: %s (%d files) -> %s' % (value, len(files), OUT_FILE))


if __name__ == '__main__':
    main()
