# -*- coding: utf-8 -*-
# M3 步骤 2.0：注册表 Lua 路径 -> LuaKeys.g.cs 生成器（设计方案 §277 收口先例）。
# **自动发现版（2026-09-10）**：不硬编码注册表文件名——扫描 Data 目录全部 xlsx（跳过 __*.xlsx），
# 凡 `##var` 表头含 `lua_path` / `entry` 列即认定为注册表表（xlsx 改名/新增注册表表零改动；
# 重命名 xlsx 的唯一联动点是 __tables__.xlsx 的 input_file 列，与本脚本无关）。
# 按"根.名字"两段式校验（根限定 UI/Content/Strategies），未知根/重名直接抛（fail the build）。
import glob
import openpyxl
import os
import re

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Data")
# 2026-09-19 目录重排跟进：LiteGame/Scripts/{Runtime,Editor,DevHUD} 已平铺为 LiteGame/{Runtime,Editor,DevHUD}
OUT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "..", "Assets", "LiteGame", "Runtime", "Shell", "Bridge", "Generated", "LuaKeys.g.cs")

PATH_FIELDS = ("lua_path", "entry")               # 注册表路径列字段名
ROOTS = ("UI", "Content", "Strategies")           # §4.4 三个固定根
PATH_RE = re.compile(r"^(?P<root>[A-Za-z_]\w*)\.(?P<name>[A-Za-z_]\w*)$")


def collect():
    paths = []                                    # [(root, name, raw)]
    workbooks = sorted(glob.glob(os.path.join(DATA_DIR, "*.xlsx")))
    for full in workbooks:
        filename = os.path.basename(full)
        if filename.startswith("__"):             # 表单注册/枚举/bean 元文件
            continue
        wb = openpyxl.load_workbook(full)
        ws = wb.active
        header_row = None
        columns = {}
        for i, row in enumerate(ws.iter_rows(values_only=True), start=1):
            first = str(row[0]) if row and row[0] is not None else ""
            if first == "##var":                  # 字段名行（Luban 表头约定）
                header_row = i
                for j, cell in enumerate(row):
                    if cell is not None:
                        columns[str(cell).strip()] = j + 1
                break
        if header_row is None:
            print("skip (no ##var header): %s" % filename)
            continue
        path_cols = [columns[f] for f in PATH_FIELDS if f in columns]
        if not path_cols:
            print("skip (no path column): %s" % filename)
            continue
        for row in ws.iter_rows(min_row=header_row + 1, values_only=True):
            first = str(row[0]) if row and row[0] is not None else ""
            if first.startswith("##"):            # 跳过 ##type / ## 注释行
                continue
            for col in path_cols:
                raw = str(row[col - 1]).strip() if col - 1 < len(row) and row[col - 1] is not None else ""
                if not raw:
                    continue                      # 空路径 = 留空用 C# 默认实现（合法）
                m = PATH_RE.match(raw)
                if not m or m.group("root") not in ROOTS:
                    raise SystemExit("gen_lua_keys: 未知根或非法两段式路径 '%s'（%s）——根限定 %s"
                                     % (raw, filename, ROOTS))
                paths.append((m.group("root"), m.group("name"), raw))
    return paths


def emit(paths):
    by_root = {}
    for root, name, raw in paths:
        if root not in ROOTS:                     # 纵深防御：绕过 collect 的直调也拦
            raise SystemExit("gen_lua_keys: 未知根 '%s'（%s）——根限定 %s" % (root, raw, ROOTS))
        seen = by_root.setdefault(root, {})
        if name in seen and seen[name] != raw:
            raise SystemExit("gen_lua_keys: 重名冲突 '%s.%s'" % (root, name))
        seen[name] = raw

    lines = []
    lines.append("// <auto-generated: Luban/gen_lua_keys.py —— DO NOT EDIT。源：注册表 xlsx 路径列；重跑 gen.bat 再生。>")
    lines.append("namespace LiteGame")
    lines.append("{")
    lines.append("    /// <summary>注册表 Lua 路径常量（生成物，2026-09-10 决策：收口散落字符串路径，设计方案 §277）。</summary>")
    lines.append("    public static class LuaKeys")
    lines.append("    {")
    for root in ROOTS:
        names = by_root.get(root, {})
        if not names:
            continue
        lines.append("        public static class %s" % root)
        lines.append("        {")
        for name in sorted(names):
            lines.append('            /// <summary>%s.%s</summary>' % (root, name))
            lines.append('            public const string %s = "%s.%s";' % (name, root, name))
        lines.append("        }")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    paths = collect()
    content = emit(paths)
    os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write(content)
    print("LuaKeys.g.cs written: %d paths -> %s" % (len(paths), OUT_FILE))


if __name__ == "__main__":
    main()
