using System;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace LiteSim.Editor
{
    /// <summary>
    /// SimTrig 查表生成器（《M7 实施指导》§2.2）。
    /// 菜单「LiteSim/生成 SimTrig 查表」→ 产出并入库 <c>Assets/LiteSim/Core/Scripts/SimTrigTables.cs</c>。
    ///
    /// 纪律（§2.1 硬规则）：生成期允许 <c>System.Math</c>（double）填表；运行期严禁超越函数（纪律扫描 R1 执行）。
    /// 幂等：固定格式 + 固定顺序 → 重复执行产出逐字节一致（验收项）。
    /// </summary>
    public static class SimTrigTableGenerator
    {
        private const int TableSize = 4096;
        private const int PerLine = 8;
        private const string OutputPath = "Assets/LiteSim/Core/Scripts/SimTrigTables.cs";

        [MenuItem("LiteSim/生成 SimTrig 查表")]
        public static void Generate()
        {
            string content = BuildContent();
            File.WriteAllText(OutputPath, content, new UTF8Encoding(false));
            AssetDatabase.Refresh();
            Debug.Log("[LiteSim] SimTrig 查表已生成：" + OutputPath + "（" + TableSize + " 项）");
        }

        /// <summary>
        /// 纯函数：构建生成物文本。固定格式（G9 + InvariantCulture）+ 固定顺序 → 幂等。
        /// 与 Runtime 侧 SimTrig 的常量（HalfPi 等）保持同一约定。
        /// </summary>
        public static string BuildContent()
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated>\n");
            sb.Append("// 生成物——请勿手改。\n");
            sb.Append("// 由 Editor 菜单「LiteSim/生成 SimTrig 查表」产出（SimTrigTableGenerator）。\n");
            sb.Append("// 表：SinTable[" + TableSize + "] 覆盖 [0, π/2]，SinTable[i] = (float)Math.Sin(i * (π/2) / (TableSize - 1))。\n");
            sb.Append("// 生成期允许 System.Math（double）填表；运行期严禁超越函数（纪律扫描 R1 执行）。\n");
            sb.Append("// </auto-generated>\n");
            sb.Append("namespace LiteSim\n");
            sb.Append("{\n");
            sb.Append("    public static class SimTrigTables\n");
            sb.Append("    {\n");
            sb.Append("        /// <summary>sin 查表：覆盖 [0, π/2]，" + TableSize + " 项，线性插值（生成物）。</summary>\n");
            sb.Append("        public static readonly float[] SinTable = new float[" + TableSize + "]\n");
            sb.Append("        {\n");

            for (int i = 0; i < TableSize; i++)
            {
                float v = (float)Math.Sin(i * (Math.PI / 2.0) / (TableSize - 1));
                if (i % PerLine == 0) sb.Append("            ");
                sb.Append(v.ToString("G9", CultureInfo.InvariantCulture)).Append('f');
                bool lineEnd = (i % PerLine == PerLine - 1) || (i == TableSize - 1);
                sb.Append(lineEnd ? ",\n" : ", ");
            }

            sb.Append("        };\n");
            sb.Append("    }\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }
}
